version: "3.7"

services:

  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./webroot:/var/www/myapp
      - ./logs:/var/log/nginx:rw
      - ./config/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:fpm
    volumes:
      - ./webroot:/var/www/myapp
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server"]
    volumes:
      - ./redis-data:/data

  composer:
    image: composer
    command: ["composer", "install"]
    volumes:
      - ./webroot:/app
